export enum Constants {
  API_VERSION = 4,
  BASE_URL = 'https://vinehelper.ovh',
  CONSENSUS_FEES = 0,
  CONSENSUS_NO_FEES = 1,
  DEBUGGER_TITLE = "Vine Helper - Debugger",
  DISCARDED_ORDER_FAILED = 4,
  DISCARDED_OWN_VOTE = 2,
  DISCARDED_WITH_FEES = 1,
  GDPR_TITLE = "Vine Helper - GDPR",
  NO_CONSENSUS = '',
  NOT_DISCARDED = 0,
  NOT_DISCARDED_NO_FEES = -1,
  NOT_DISCARDED_NO_STATUS = -3,
  NOT_DISCARDED_ORDER_SUCCESS = -4,
  NOT_DISCARDED_OWN_VOTE = -2,
  VERSION_MAJOR_CHANGE = 3,
  VERSION_MINOR_CHANGE = 2,
  VERSION_NO_CHANGE = 0,
  VERSION_REVISION_CHANGE = 1,
  VINE_INFO_TITLE = "Vine Helper update info",
  VOTING_TITLE = "Vine Helper - voting feature",
  WSS_URL = 'https://wss.vinehelper.ovh',
}